### ISSUE TITLE
adding new users when Fink is using '--yes' mode fails if user not present in passwd-fink

### ISSUE THREAD

**Issue by nieder** [fink/passwd#3]
I was doing a leave alone build and it tried to install passwd-quagga.  The install log looked like this:

~~~~
Looking for quagga entry in /sw/etc/passwd-fink...No entry for quagga in /sw/etc/passwd-fink
Enter a value manually.
UID  is use.
UID  is use.
UID  is use.
UID  is use.
[repeat for some 3 million more lines]
~~~~

Other users in the passwd-* family like opennms, postgres, and avahi installed correctly.  The difference is that quagga is not in /sw/etc/{group,passwd}-fink.  Is this error 
1. a bug in the passwd scripts (user addition should work for non-listed users)
2. just missing entries in passwd's /sw/etc/{group,passwd}-fink files?

Note that this is only an issue in --yes mode.

**Comment by akhansen** [comment]
Just rediscovered this issue when I built redis for a tracker submission.

**Comment by akhansen** [comment]
Done apart from some ordering cleanup.
